### PR TITLE
[WIP] travis: Add Travis configuration for build testing

### PR DESCRIPTION
**Pull request by paulmenzel**

### CODE REVIEW

**Comment by paulmenzel** [comment]
Doesn’t work yet. So still WIP. :(

**Comment by mariux** [comment]
i think this pull request is a bit out of control ;) please reopen once done ;)

**Comment by mariux** [comment]
working .travis.yml now in master..

**Comment by paulmenzel** [comment]
@mariux, thank you, but if you had looked in the upstream tree at github.molgen.mpg.de than there are already a lot of the commits you made, and now we have more work resolving merge conflicts. :( I only opened the pull request here, as Travis CI works out of the box with github.com.

I’ll start a discussion about further MXQ development soon.

**Comment by mariux** [comment]
revert ca3cc47590c92f4b969661b1e739b8465b1f40f4
and merge... no conflicts and travis is not failing anymore.. because it is for current upstream..

your gcc5 fixes seem to break gcc4 compilation...

i just removed all the inline functions... if there are performance issues just fix those when they occur.. if ever..

**Comment by paulmenzel** [comment]
Thank you. I probably exaggerated.

**Pull request closed without merging**
